import SessionProvider from '../Context/SessionProvider'
import ThemeProvider from '../Context/ThemeProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import { ReduxProvider } from '@/redux/provider'
import styles from "./styles.module.css"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Melodia',
  description: 'Generated by create next app',
}



export default async function RootLayout({ children }) {
  const session =await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.bodyScrollBar}`}>
        <SessionProvider session={session}>
          <ReduxProvider>
            <ThemeProvider enableSystem={false} attribute='class'>
            
              {children}
            </ThemeProvider>
          </ReduxProvider>
        </SessionProvider>
        </body>
    </html>
  )
}
